### ISSUE TITLE
A pom.base.Parentable inside a def is unable to override its parent

### ISSUE THREAD

**Issue by terry-chiu-certn** [nickroeker/e2e.common#1]
I did not step through the code in e2e.common, but reading the code, I think the root problem may be...

The following line seems to do the proper parent overriding:
https://github.com/nickroeker/e2e.common/blob/43b78ae3c7debf95fcebca42246ce866093b04ef/e2e/common/modelling.py#L99

However, a bit further down at https://github.com/nickroeker/e2e.common/blob/43b78ae3c7debf95fcebca42246ce866093b04ef/e2e/common/modelling.py#L112, if I didn't misinterpret the nested def inside `stitch_parent`, it will actually assign the containing class to the parent.

The expectation is that one should be able to specify any parent on a `NamedParentable`.

**Comment by nickroeker** [comment]
Thank you! This is fixed and released in `0.1.4`
